# Generated by Django 4.1.7 on 2023-03-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_wishlist_cartitem_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Kannur', 'Kannur'), ('Kochi', 'Kochi'), ('Hubli', 'Hubli'), ('Ernakulam', 'Ernakulam'), ('Kozhikkode', 'Kozhikkode'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator'), ('Hydrabad', 'Hydrabad'), ('Banglore', 'Banglore'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=255),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
