# Generated by Django 4.1.7 on 2023-03-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_address_city_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Banglore', 'Banglore'), ('Kochi', 'Kochi'), ('Madurai', 'Madurai'), ('Hydrabad', 'Hydrabad'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hubli', 'Hubli'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator')], max_length=255),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
