# Generated by Django 4.1.7 on 2023-03-28 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_order_alter_address_city_payment_orderproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam'), ('Kochi', 'Kochi'), ('Coimbator', 'Coimbator'), ('Hydrabad', 'Hydrabad'), ('Kannur', 'Kannur'), ('Kozhikkode', 'Kozhikkode'), ('Hubli', 'Hubli'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Madurai', 'Madurai')], max_length=255),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.orderproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
