# Generated by Django 4.1.7 on 2023-04-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_address_city_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Madurai', 'Madurai'), ('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Kochi', 'Kochi'), ('Ernakulam', 'Ernakulam'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Coimbator', 'Coimbator'), ('Banglore', 'Banglore')], max_length=255),
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
