# Generated by Django 4.1.7 on 2023-04-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_address_city_alter_productreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Hubli', 'Hubli'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Madurai', 'Madurai'), ('Hydrabad', 'Hydrabad'), ('Kochi', 'Kochi'), ('Kannur', 'Kannur'), ('Banglore', 'Banglore'), ('Kozhikkode', 'Kozhikkode'), ('Coimbator', 'Coimbator'), ('Ernakulam', 'Ernakulam')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Average', max_length=50),
        ),
    ]
