# Generated by Django 4.1.7 on 2023-04-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_address_city_alter_productreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Kochi', 'Kochi'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Hubli', 'Hubli'), ('Banglore', 'Banglore'), ('Kozhikkode', 'Kozhikkode')], max_length=255),
        ),
    ]
